### ISSUE TITLE
I found your repo !!!

### ISSUE THREAD

**Issue by mrfambo** [hnrq/rich-text-editor#1]
Well i just searched wysiwyg on Github Search and saw your repository was recently updated. Are you working on something related to wysiwyg. I am looking for making a Drag and Drop based page builder using React Based Components. If somehow things match, we can collaborate !!!

**Comment by AlberoneRamos** [comment]
How's it going, mate? This repository is actually just a "test drive". I'm trying out Slate and Draft just for fun, but your project looks really interesting! But, for now, I'm really busy with college and work stuff. Reach me out when you start your project, because I'm really interested in following your progress on this journey
